/*
 * NewJFrame.java
 *
 * Created on 2008年2月14日, 下午4:45
 */
package downloadmp3;

import java.io.File;
import java.io.IOException;
import java.lang.Runnable;
import java.lang.Thread;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import java.awt.Cursor;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author  oneleaf
 */
public class MainFrame extends javax.swing.JFrame {

    JFileChooser jf;

    /** Creates new form NewJFrame */
    public MainFrame() {
        initComponents();
        jLabel_Site.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        SpinnerNumberModel model = new SpinnerNumberModel(DownTask.getInstance().getPOOL_SIZE(), 1, 500, 1);
        jSpThreadCount.setModel(model);
        jTextField_SavePath.setText(DownTask.getInstance().getSavePath());
        MainFrameUI.setTaskTable(jTable_TaskList);
        MainFrameUI.setDowningTable(jTable_Download);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TaskList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Download = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField_SavePath = new javax.swing.JTextField();
        jProgressBar_DownLoad = new javax.swing.JProgressBar();
        jLabel_Site = new javax.swing.JLabel();
        jBDir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_StartDown = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Url = new javax.swing.JTextField();
        jButton_getTaskList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_SelectAll = new javax.swing.JButton();
        jButton_SelectNone = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSpThreadCount = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("百度歌曲下载器 1.1.2");

        jSplitPane1.setDividerLocation(160);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jTable_TaskList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_TaskList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTable_Download.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Download);

        jSplitPane1.setRightComponent(jScrollPane2);

        jTextField_SavePath.setEditable(false);

        jLabel_Site.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Site.setText("<html><a href=\"http://www.optool.cn\">无法下载?点击 http://www.optool.cn 查看最新版本.</a></html>");
        jLabel_Site.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SiteMouseClicked(evt);
            }
        });

        jBDir.setText("浏览");
        jBDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDirActionPerformed(evt);
            }
        });

        jLabel5.setText("保存目录：");

        jLabel4.setText("进度：");

        jButton_StartDown.setText("开始下载");
        jButton_StartDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Site, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SavePath, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar_DownLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_StartDown, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_SavePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jProgressBar_DownLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel_Site))
                    .addComponent(jButton_StartDown, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "清空地址", "热门TOP500", "新歌TOP100", "经典老歌TOP500", "流金岁月" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("网址：");

        jButton_getTaskList.setText("解析");
        jButton_getTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_getTaskListActionPerformed(evt);
            }
        });

        jLabel2.setText("下载列表：");

        jButton_SelectAll.setText("全选");
        jButton_SelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelectAllActionPerformed(evt);
            }
        });

        jButton_SelectNone.setText("全不选");
        jButton_SelectNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelectNoneActionPerformed(evt);
            }
        });

        jLabel8.setText("并发下载：");

        jSpThreadCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpThreadCountStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_SelectAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_SelectNone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(jTextField_Url, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_getTaskList, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_getTaskList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_SelectAll, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton_SelectNone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jSpThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jBDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDirActionPerformed
        jf.setCurrentDirectory(new File(DownTask.getInstance().getSavePath()));
        if (jf.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        String savePath = jf.getSelectedFile().toString();
        jTextField_SavePath.setText(savePath);
        DownTask.getInstance().setSavePath(savePath);
        
    }//GEN-LAST:event_jBDirActionPerformed

    private void jSpThreadCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpThreadCountStateChanged
        DownTask.getInstance().setPOOL_SIZE(Integer.parseInt(jSpThreadCount.getValue().toString()));
    }//GEN-LAST:event_jSpThreadCountStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String url = "";
        if (jComboBox1.getSelectedIndex() == 1) {
            url = "http://list.mp3.baidu.com/topso/mp3topsong.html?id=1?top2";
        } else if (jComboBox1.getSelectedIndex() == 2) {
            url = "http://list.mp3.baidu.com/list/newhits.html?id=1?top1";
        } else if (jComboBox1.getSelectedIndex() == 3) {
            url = "http://list.mp3.baidu.com/list/oldsong.html?top6";
        } else if (jComboBox1.getSelectedIndex() == 4) {
            url = "http://list.mp3.baidu.com/list/liujinsuiyue.html?top24";
        } else if (jComboBox1.getSelectedIndex() == 5) {
            url = System.getProperty("user.home") + File.separatorChar + "music/toDownload.list";
        }
        jTextField_Url.setText(url);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton_getTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_getTaskListActionPerformed
        try {
            String url = jTextField_Url.getText().trim();
//            if (url == null || !url.toLowerCase().contains("baidu.com")) {
            if (url == null || url.equals("")) {
                JOptionPane.showMessageDialog(this, "地址没有输入，或者不是一个有效的百度音乐列表地址", "错误信息", JOptionPane.WARNING_MESSAGE);
                return;
            }
            DownTask.getInstance().getTaskList(url);
            jTable_TaskList.updateUI();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "获取错误:" + ex.getMessage(), "错误信息", JOptionPane.WARNING_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_getTaskListActionPerformed

    /**
     * 全选
     */
    private void jButton_SelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelectAllActionPerformed
        for (TaskInfo task : DownTask.getInstance().getTaskList()) {
            task.isEnabled = true;
        }
        jTable_TaskList.updateUI();
    }//GEN-LAST:event_jButton_SelectAllActionPerformed

    /**
     * 全不选
     */
    private void jButton_SelectNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelectNoneActionPerformed
        for (TaskInfo task : DownTask.getInstance().getTaskList()) {
            task.isEnabled = false;
        }
        jTable_TaskList.updateUI();
    }//GEN-LAST:event_jButton_SelectNoneActionPerformed

    /**
     * 以之前获得的下载任务列表为输入参数，开始下载
     */
    private void jButton_StartDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartDownActionPerformed
        try {
            jButton_StartDown.setEnabled(false);
            jBDir.setEnabled(false);
            DownTask.getInstance().downloadAllMp3();
            jProgressBar_DownLoad.setMinimum(0);
            jProgressBar_DownLoad.setMaximum(DownTask.getInstance().allTaskCount);
            jProgressBar_DownLoad.setStringPainted(true);
            final ScheduledThreadPoolExecutor scheduler = (ScheduledThreadPoolExecutor) Executors.newScheduledThreadPool(1);
            Runnable runnable =
                    new Runnable() {

                        public void run() {
                            if (DownTask.getInstance().getExecutorService().isTerminated()) {
                                jButton_StartDown.setEnabled(true);
                                jBDir.setEnabled(true);
                                scheduler.shutdown();
                            }
                            try {
                                jTable_Download.updateUI();
                                jProgressBar_DownLoad.setValue(DownTask.getInstance().finishTaskCount);
                                Thread.sleep(1000);
                            } catch (Exception e) {
                            	e.printStackTrace();
                            }
                        }
                    };

            scheduler.scheduleAtFixedRate(runnable, 5, 1, TimeUnit.SECONDS);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "获取错误:" + ex.getMessage(), "错误信息", JOptionPane.WARNING_MESSAGE);
            ex.printStackTrace();
        }
}//GEN-LAST:event_jButton_StartDownActionPerformed

    private void jLabel_SiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SiteMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://www.optool.cn"));//GEN-LAST:event_jLabel_SiteMouseClicked
        } catch (Exception ex) {
            try {
                Runtime.getRuntime().exec("firefox http://www.optool.cn");
            } catch (IOException ex1) {
            }
        }
    }                                        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDir;
    private javax.swing.JButton jButton_SelectAll;
    private javax.swing.JButton jButton_SelectNone;
    private javax.swing.JButton jButton_StartDown;
    private javax.swing.JButton jButton_getTaskList;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Site;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar_DownLoad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpThreadCount;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable_Download;
    private javax.swing.JTable jTable_TaskList;
    private javax.swing.JTextField jTextField_SavePath;
    private javax.swing.JTextField jTextField_Url;
    // End of variables declaration//GEN-END:variables
}
