/*
 * Created on Apr 22, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.jlx.filter;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;

/**
 * @author henry jiang
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
public class LogFilter implements Filter {
	
	private String IP = null;
	private String sayhello = null;
	private FilterConfig  filterConfig = null;
	
	public void init(FilterConfig config) throws ServletException {
		this.IP = config.getInitParameter("IP");
		this.sayhello = config.getInitParameter("SayHello");
		this.filterConfig = config;
		
	}

	public void doFilter(ServletRequest request, ServletResponse response,
			FilterChain chain) throws IOException, ServletException {
		if(IP.equals("true")){
			this.filterConfig.getServletContext().log("A connection from " + request.getRemoteAddr()+ ":" +request.getRemotePort());
			System.out.println("A connection from " + request.getRemoteAddr()+ ":" +request.getRemotePort());
		}
		if(sayhello.equals("true")){
			this.filterConfig.getServletContext().log("Welcome!!!");
			System.out.println("Welcome!!!");
		}
		chain.doFilter(request,response);
		
	}

	public void destroy() {
		//TODO Method stub generated by Lomboz
	}

	public FilterConfig getFilterConfig() {
		//TODO Method stub generated by Lomboz
		return null;
	}

	public void setFilterConfig(FilterConfig config) {
		//TODO Method stub generated by Lomboz
	}
}